dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: fmtok8s-agenda
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- name: fmtok8s-api-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.34
- name: fmtok8s-c4p
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.19
- name: fmtok8s-email
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: fmtok8s-monolith
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: fmtok8s-tests
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- alias: zeebe-operator
  name: zeebe-operator
  repository: http://helm.zeebe.io
  version: 0.0.72
